export enum MessageTypes {
  GET_MAIN_NODE = "CONNECT_TO_MAIN_NODE",
  BLOCK = "BLOCK",
  USER = "USER",
  JOIN = "JOIN",
  TRANSACTION = "TRANSACTION",
  SUCCESSFUL_VERIFY_NEW_NODE = "SUCCESSFUL_VERIFY_NEW_NODE",
}
