export enum MessageTypes {
  GET_MAIN_NODE = "CONNECT_TO_MAIN_NODE",
  BLOCK = "BLOCK",
  USER = "USER",
  JOIN = "JOIN",
  TRANSACTION = "TRANSACTION",
  SUCCESSFUL_VERIFY_NEW_NODE = "SUCCESSFUL_VERIFY_NEW_NODE",
  CONNECT_NODE = "CONNECT_NODE",
  NODES_VERIFY_BLOCK = "NODES_VERIFY_BLOCK",
}
